version: "3"
services:
  server:
    build: .
    image: chipsenkbeil/distant_nvim_test
    command: sudo /usr/sbin/sshd -D -e
  client:
    build: .
    image: chipsenkbeil/distant_nvim_test
    depends_on:
      - server
    environment:
      - DISTANT_HOST=server
      - DISTANT_PORT=22
      - DISTANT_BIN=/usr/local/bin/distant
    command: sh -c "cd app && make test"
