name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test-docker
      - name: Check running containers
        run: docker ps -a

