name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: distant_nvim_test
          push_image_and_stages: on:push
      - name: Run tests
        run: make test-docker
      - name: Check running containers
        run: docker ps -a

