name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull latest images to build
        run: docker-compose pull
      - name: Perform caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Run tests
        run: make test-docker
      - name: Check running containers
        run: docker ps -a

